### PR TITLE
Track forge commits to main

### PR DESCRIPTION
**Pull request by meenakshiramanathan1**

### CODE REVIEW

**Review by nvukobratTT — CHANGES_REQUESTED** [review]
Hey Meenakshi, we should cherry-pick changes from Buda (main branch) to the Forge (forge_track) branch :))

Buda vs Forge differ now, and we need to just cherry-pick the ones that are valid ops fixes :))

Afterwards, I can do a switch between branch names :))

**Comment by nvukobratTT** [comment]
Is this PR redundant? I see this one opened as well: https://github.com/tenstorrent/tt-tvm/pull/36

**Comment by meenakshiramanathan1** [comment]
Updated in #36

**Comment by meenakshiramanathan1** [comment]
Updated in https://github.com/tenstorrent/tt-tvm/pull/36

**Pull request closed without merging**
